"""The narrative eval's facts sheets: regenerated by script, and what is in them."""

import importlib.util
import json
import re
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest
from conftest import empty_database
from sqlalchemy import Engine

from feasibility.llm.facts import Facts
from feasibility.llm.narrative import CASES_FILE, check_text
from feasibility.llm.narrative_check import check_narrative

SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "build_narrative_cases.py"
PERSONAL_DATA_NAME = re.compile(r"owner|mail|phone|email|agent|office|taxpayer|legal")


def _script() -> Any:
    spec = importlib.util.spec_from_file_location("build_narrative_cases", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def regenerated(migrated_engine: Engine) -> Iterator[str]:
    empty_database(migrated_engine)
    yield _script().render(_script().build(migrated_engine))
    empty_database(migrated_engine)


def _cases() -> list[dict[str, Any]]:
    return list(json.loads(CASES_FILE.read_text(encoding="utf-8")))


def test_the_committed_file_is_what_the_script_writes_byte_for_byte(regenerated: str) -> None:
    assert CASES_FILE.read_text(encoding="utf-8") == regenerated


def test_the_suite_has_thirteen_cases_in_three_groups() -> None:
    sources = [case["source"] for case in _cases()]

    assert len(_cases()) == 13
    assert [sources.count(s) for s in ("workbook", "snapshot", "adversarial")] == [3, 6, 4]
    assert len({case["id"] for case in _cases()}) == 13


def test_every_facts_sheet_validates_and_round_trips() -> None:
    for case in _cases():
        facts = Facts.model_validate(case["facts"])

        assert facts.as_inputs() == case["facts"], case["id"]


def test_the_workbook_cases_are_s1_to_s3_and_s3_is_the_loss() -> None:
    by_id = {case["id"]: case for case in _cases()}

    assert by_id["s1"]["facts"]["figures"]["profit"] == "$107,560.14"
    assert by_id["s3"]["must_cover"] == ["no_viable_offer", "negative_profit"]
    assert "max_offer" not in by_id["s3"]["facts"]["figures"]


def test_the_snapshot_cases_are_the_six_demo_accounts_with_their_signals() -> None:
    by_id = {case["id"]: case for case in _cases()}
    expected = {
        "snap-051": {"plans_or_permits", "protected_trees"},
        "snap-004": {"teardown_language", "as_is_sale", "price_reduced"},
        "snap-052": {"deed_restrictions", "flood_or_drainage"},
        "snap-002": {"tenant_occupied", "conservation_or_historic_district"},
        "snap-006": {"environmental_hazard", "easement_or_encroachment"},
        "snap-015": {"seller_financing", "teardown_language"},
    }

    for case_id, codes in expected.items():
        assert {s["code"] for s in by_id[case_id]["facts"]["signals"]} == codes, case_id


def test_the_adversarial_cases_plant_a_canary_and_a_number_in_a_quote() -> None:
    injected = [case for case in _cases() if case["injection"]]

    assert [case["id"] for case in injected] == ["adv-injected-quote", "adv-second-injection"]
    for case in injected:
        quotes = " ".join(s["quote"] or "" for s in case["facts"]["signals"])
        assert case["injection"]["canary"] in quotes
        assert case["injection"]["number"] in quotes


def test_the_gis_case_carries_the_flag_and_must_be_covered() -> None:
    case = next(c for c in _cases() if c["id"] == "adv-gis-group")

    assert "gis_group" in [f["code"] for f in case["facts"]["flags"]]
    assert case["must_cover"] == ["gis_group"]


def test_must_cover_codes_are_codes_the_facts_name() -> None:
    for case in _cases():
        facts = Facts.model_validate(case["facts"])

        assert set(case["must_cover"]) <= set(facts.codes), case["id"]


def test_no_sheet_holds_an_address_or_remarks_beyond_a_quote() -> None:
    for case in _cases():
        text = json.dumps(case["facts"])

        assert not re.search(r"\d{3,5} [A-Z][a-z]+ (Ave|St|Trl|Ln|Dr|Rd)", text), case["id"]
        assert "address" not in text and "remarks" not in text


def test_no_key_matches_the_personal_data_name_pattern() -> None:
    def keys(value: Any) -> list[str]:
        if isinstance(value, dict):
            return [*value, *(k for item in value.values() for k in keys(item))]
        if isinstance(value, list):
            return [k for item in value for k in keys(item)]
        return []

    assert [k for k in keys(_cases()) if PERSONAL_DATA_NAME.search(k)] == []


def test_a_plain_summary_of_each_cases_own_figures_passes_the_check() -> None:
    """The cases are solvable: copying the sheet's figures verbatim is always accepted."""
    from feasibility.llm.narrative_check import NarrativeDraft

    for case in _cases():
        facts = Facts.model_validate(case["facts"])
        draft = NarrativeDraft(
            summary="; ".join(facts.figures.values()), risks=[], checks_before_offer=[]
        )

        assert check_narrative(draft, facts).passed, case["id"]


# --- the debug helper ---------------------------------------------------------------------------


def test_check_text_accepts_exact_figures_and_names_their_keys() -> None:
    assert check_text("Profit is $107,560.14 at a 7.57% margin.", "S1") == (
        "accepted: margin=7.57%, profit=$107,560.14"
    )


def test_check_text_rejects_a_rounded_figure_and_says_which() -> None:
    assert check_text("Profit is about $108k.", "S1") == "rejected: unlisted_figure: $108k"


def test_check_text_refuses_an_unknown_case() -> None:
    with pytest.raises(ValueError, match="no case 'nope'"):
        check_text("x", "nope")
